version: '3'
services:
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:8.0.21
        container_name: mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=samalex
            - MYSQL_PASSWORD=root
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"